version: "3"

# What we want to run:
# - DNS service
# - nginx-proxy for forwarding requests
# - VPN service
# - Catch-all mailserver
# - Backup service for iPhones
# - TimeMachine backup service


services:
  dns:
    container_name: dns
    image: cytopia/bind:0.28
    hostname: bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    dns:
      - 127.0.0.1
    environment:
      - DNS_A='*.hyc=192.168.2.70'
      - DNS_FORWARDER=192.168.1.1
      - DOCKER_LOGS=1
      - DEBUG_ENTRYPOINT=2
    restart: always
