version: "3"
services:
  dns:
    container_name: dns
    image: cytopia/bind:0.28
    hostname: bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - "53"
    environment:
      - DNS_A=*.local.premia.tmprly.com=164.92.151.1
      - DNS_FORWARDER=1.1.1.1
      - DOCKER_LOGS=1
      - DEBUG_ENTRYPOINT=2
      - ALLOW_RECURSION=any
      - ALLOW_QUERY=any
    restart: always

networks:
  default:
    external:
      name: swarm