version: "3"
services:
  users:
    image: lscr.io/linuxserver/openssh-server
    container_name: test-user
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.users.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.users.entrypoints=ssh"
      - "traefik.tcp.routers.users.service=users-service"
      - "traefik.tcp.services.users-service.loadbalancer.server.port=2222"
    restart: always
    environment:
      - "USER_PASSWORD=test"
      - "USER_NAME=test"
      - "PASSWORD_ACCESS=true"
      - "SUDO_ACCESS=true"
    ports:
      - 2225:2222
    volumes:
      - "/home/mklasen/halcyon-wp/users/defaults/custom-cont-init.d:/config/custom-cont-init.d"
      - "/home/mklasen/halcyon-wp/users/defaults/ssh_config:/config/ssh_host_keys/sshd_config"
      - "/home/mklasen/halcyon-wp/users/defaults/web:/config/web"
      - "/home/mklasen/halcyon-wp/users/defaults/.profile:/config/.profile"
      - "/home/mklasen/halcyon-wp/users/home/test-user/config:/config"
      - "/home/mklasen/halcyon-wp/users/welcome.txt:/etc/motd"
networks:
  default:
    external:
      name: swarm